[package]
name = "text-editor"
version = "0.1.0"
edition = "2021"
author = ["Aryan Tikarya"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1"
